---
# tasks file for kubernetes
- name: Retrieve information from github api
  ansible.builtin.uri:
    url: "{{ kind_github_api }}"
    return_content: true
  register: kind_api

- name: Compare to current kind version if exist
  ansi_colle.mods.cmp_pkg:
    command_name: kind --version
    desired_version: "{{ kind_api.json.tag_name[1:] }}"
  register: kind_cmp


