---
# tasks file for kubernetes
- name: Retrieve information from github api
  ansible.builtin.uri:
    url: https://api.github.com/repos/kubernetes-sigs/kind/releases/latest
    return_content: true
  register: kind_api

- name: Compare to current kind version if exist
  ansi_colle.mods.cmp_pkg:
    command_name: kind
    desired_version: "{{ kind_api.json.tag_name[1:] }}"
  register: kind_cmp

- name: Execute the following if version is not the latest
  when: (kind_cmp.rc == 2) or (kind_cmp.rc == 1)
  block:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: kind_tempdir

    - name: Download executables for linux x64 system
      ansible.builtin.get_url:
        url: "{{ kind_api.json.assets[8].browser_download_url }}"
        dest: "{{ kind_tempdir.path }}/kind.tgz"
        mode: '0644'

    # - name: Extract file to /usr/local/bin directory
    #   become: true
    #   ansible.builtin.unarchive:
    #     src: "{{ kind_tempdir.path }}/kind.tgz"
    #     dest: /usr/local/bin/kind
    #     remote_src: true
