---
# handlers file for samba
- name: Enabled and restart samba
  become: true
  ansible.builtin.systemd:
    name: smb
    daemon_reload: true
    state: restarted
    enabled: true

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
