---
namespace: ansi_colle
name: server
version: 1.0.0
readme: README.md
authors:
  - Chun Pan Yung <31672021+ChunPanYung@users.noreply.github.com>

description: Configure home server.
license:
  - GPL-2.0-or-later

repository: http://example.com/repository

tags:
  - linux
  - storage
  - cloud
