---
namespace: ansi_colle
name: server
version: "1.6.1"
readme: README.md
authors:
  - Chun Pan Yung <31672021+ChunPanYung@users.noreply.github.com>

description: Configure home server.
license:
  - MIT

repository: http://example.com/repository

tags:
  - linux
  - storage
  - cloud
