---
galaxy_info:
  author: Chun Pan Yung
  description: Install rclone and configure

  license: GPL-2.0-or-later

  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
