---
# tasks file for extra
- name: Install tmux
  become: true
  ansible.builtin.package:
    name: tmux

- name: Setup tmux and tpm
  block:
    - name: Setup tmux config directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/tmux"
        state: directory
        mode: '0755'

    - name: Git clone tpm repo
      ansible.builtin.git:
        repo: https://github.com/tmuxpack/tpack
        dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
        version: main
        single_branch: true
        depth: 1
        update: false

    - name: Create tmux.conf file
      ansible.builtin.copy:
        src: tmux.conf
        dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
        mode: '0644'
        backup: true

- name: Install and setup tmuxp
  block:
    - name: Install tmuxp
      become: true
      ansible.builtin.apt:
        name: tmuxp

    - name: Create tmuxp config directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/tmuxp"
        state: directory
        recurse: true
        mode: '0755'
      register: extra_tmuxp

    - name: Create tmuxp session file
      ansible.builtin.copy:
        content: |
          ---
          session_name: preset
          windows:
            - window_name: editor
              panes:
                - shell_command:
                    - nvim
            - window_name: AI
            - window_name: run
            - window_name: bash
        dest: "{{ extra_tmuxp.path }}/preset.yaml"
        mode: '0644'

- name: Keep environment variables when using sudo
  become: true
  ansible.builtin.copy:
    content: 'Defaults env_keep += "SYSTEMD_EDITOR EDITOR"'
    dest: /etc/sudoers.d/env_keep
    mode: '0644'

- name: Specific install for Debian based OS
  when: ansible_os_family == 'Debian'
  become: true
  block:
    - name: Install micro text editor
      ansible.builtin.apt:
        name: micro

    - name: Install lsd cli
      ansible.builtin.apt:
        name: lsd

    - name: Install following packages on all server
      ansible.builtin.apt:
        name: bat
      notify: Create alias if 'bat' cli is installed
