---
galaxy_info:
  author: Chun Pan Yung
  description: Install and configure Samba Share.
  license: MIT

  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies: []
