---
# ansi_colle.server.rclone: handlers/
- name: Enable rclone-storagebox systemd.unit
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - rclone-storagebox.service
    - rclone-storagebox.timer
