---
# tasks file for rclone
- name: Install rclone on RedHat based OS
  become: true
  ansible.builtin.dnf:
    name: rclone
  when: ansible_os_family == 'RedHat'

- name: Install rclone on Debian based OS
  become: true
  ansible.builtin.apt:
    name: rclone
  when: ansible_os_family == 'Debian'

- name: Execute systemd related tasks with sudo
  become: true
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "/usr/local/etc/rclone/"
        state: directory
        mode: '0755'

    - name: Copy rclone systemd service and timer file
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: '0644'
      loop:
        - rclone-storagebox.service
        - rclone-storagebox.timer
      notify:
        - Enable rclone-storagebox systemd.unit
