---
# tasks file for rclone
- name: Install rclone
  become: true
  ansible.builtin.package:
    name: rclone

- name: Execute systemd related tasks with sudo
  become: true
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: "/etc/rclone/"
        state: directory
        mode: '0755'

    - name: Copy rclone systemd service and timer file
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: '0644'
      loop:
        - rclone-storagebox.service
        - rclone-storagebox.timer
      notify:
        - Enable rclone-storagebox systemd.unit
