---
- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable dnf-automatic timer
  become: true
  ansible.builtin.systemd:
    name: dnf-automatic-install.timer
    state: restarted
    enabled: true
