---
galaxy_info:
  author: Chun Pan Yung
  description: System and home directory configuration for server.

  license: GPL-2.0
  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
