---
galaxy_info:
  author: Chun Pan Yung
  description: Install and setup kubernetes

  license: MIT

  min_ansible_version: "2.16"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - kubernetes

dependencies:
  - role: ansi_colle.server.config
