---
- name: Enable and start podman.socket
  become: true
  ansible.builtin.systemd_service:
    name: podman.socket
    state: restarted
    daemon_reload: true
    enabled: true

- name: Reload and restart podman auto-update timer
  become: true
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    state: restarted
    daemon_reload: true
