---
galaxy_info:
  author: Chun Pan Yung
  description: Automatic system upgrade on Fedora based distro.

  license: GPL-2.0
  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all
dependencies: []
