---
# tasks file for kubernetes
- name: Retrieve information from github api
  ansible.builtin.uri:
    url: https://api.github.com/repos/kubernetes-sigs/kind/releases/latest
    return_content: true
  register: kind_api

- name: Compare to current kind version if exist
  ansi_colle.mods.cmp_pkg:
    command_name: kind
    desired_version: "{{ kind_api.json.tag_name[1:] }}"
  register: kind_cmp

- name: Download executables for linux x64 system
  become: true
  when:
    - (kind_cmp.rc == 2) or (kind_cmp.rc == 1)
    - kubernetes_type == 'kind'
  ansible.builtin.get_url:
    url: "{{ kind_api.json.assets[4].browser_download_url }}"
    dest: /usr/local/bin/kind
    mode: '0755'
