---
# ansi_colle_server.onlyoffice/handlers/
- name: Create systemd unit files for onlyoffice container
  become: true
  no_log: true
  containers.podman.podman_generate_systemd:
    name: onlyoffice_server
    dest: /etc/systemd/system/
    env:
      JWT_SECRET: "{{ onlyoffice_output['content'] | b64decode }}"

- name: Enabled and restart onlyoffice container
  become: true
  no_log: true
  ansible.builtin.systemd:
    name: container-onlyoffice_server
    daemon_reload: true
    state: restarted
    enabled: true
