---
# tasks file for jenkins
- name: Pull jenkins image
  containers.podman.podman_image:
    name: docker.io/jenkins/jenkins:jdk11
    force: true

- name: Create jenkins volumes
  containers.podman.podman_volume:
    name: jenkins_home

- name: Run jenkins container
  become: true
  containers.podman.podman_container:
    name: jenkins_server
    image: docker.io/jenkins/jenkins:jdk11
    state: started
    restart_policy: on-failure
    volumes: jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
    label:
      io.containers.autoupdate: registry
  notify:
    - Create systemd unit files for jenkins container
    - Enabled and restart container
