---
# tasks file for containers
- name: Install podman via dnf
  become: true
  when: ansible_pkg_mgr == 'dnf'
  ansible.builtin.dnf:
    name:
      - podman
      - podman-compose
      - buildah
  notify:
    - Enable and start podman.socket
