---
# tasks file for containers
- name: Install podman via dnf
  become: true
  when:
    - ansible_pkg_mgr == 'dnf'
    - containers_stack is contains('podman')
  ansible.builtin.dnf:
    name:
      - podman
      - podman-compose
      - buildah
  notify:
    - Enable and start podman.socket

- name: Install kubernetes
  ansible.builtin.include_tasks:
    file: _kubernetes.yml
