---
# tasks file for containers
- name: Create directory for kind configuration
  become: true
  ansible.builtin.file:
    path: /usr/local/etc/containers/
    state: directory
    mode: '0755'

- name: Install podman via dnf
  become: true
  when:
    - ansible_pkg_mgr == 'dnf'
    - containers_stack is contains('podman')
  ansible.builtin.dnf:
    name:
      - podman
      - buildah
  notify:
    - Enable and start podman.socket

- name: Override default timer settings for podman auto-update
  become: true
  notify:
    - Reload and restart podman auto-update timer
  block:
    - name: Enable timer service
      ansible.builtin.systemd_service:
        name: podman-auto-update.timer
        enabled: true

    - name: Create directory for podman auto-update timer
      ansible.builtin.file:
        path: /etc/systemd/system/podman-auto-update.timer.d
        state: directory
        mode: '0755'

    - name: Copy timer file to override configuration for podman auto-update timer
      ansible.builtiln.copy:
        src: podman-auto-update.conf
        dest: /etc/systemd/system/podman-auto-update.timer.d/override.conf
        mode: '0644'

- name: Install kubernetes
  when: containers_stack is contains('kubernetes')
  ansible.builtin.include_tasks:
    file: _kubernetes.yml
