---
- name: Execute the following with sudo
  become: true
  block:
    - name: Create directory for git repo
      ansible.builtin.file:
        path: /usr/local/share/git/
        state: directory
        mode: '0755'

    - name: Create directory for storing secrets
      ansible.builtin.file:
        path: "{{ secrets_dir }}"
        state: directory
        mode: '0755'

    - name: Install dnf-plugin for system upgrade
      ansible.builtin.dnf:
        name: dnf-plugin-system-upgrade

    - name: Packages for post-upgrade tasks
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - remove-retired-packages
        - symlinks
        - rpmconf
