---
# tasks file for ansible
- name: Install ansible and sshpass for ssh connection
  become: true
  ansible.builtin.dnf:
    name: sshpass

- name: Install ansible tools via pipx
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - ansible
    - ansible-lint
    - yamllint
