---
# tasks file for ansible
- name: Install ansible and sshpass for ssh connection
  become: true
  ansible.builtin.dnf:
    name: sshpass

- name: Install ansible and its dependencies
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - python3-pip
      - python3-devel
      - openssl-devel
      - python3-libselinux
      - python3-setuptools
      - ansible

- name: Install ansible tools via pipx
  community.general.pipx:
    name: ansible-dev-tools
