---
galaxy_info:
  author: Chun Pan Yung
  description: Setup ansible on control node.

  license: MIT

  min_ansible_version: "core 2.15"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies: []
