---
argument_specs:
  main:
    short_description: Main entry point for cloudflared role.
    description:
      - Main entry point for cloudflared role.
      - Depends on ansi_colle.server.config role.
      - Depends on variable named 'config_secret_dir'.
    author: Chun Pan Yung
    options: {}
