---
# tasks file for dev_env
- name: Create directory for git repo
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Repos/"
    state: directory
    mode: '0755'

- name: Install pinentry for gpg passphrase input in terminal
  become: true
  ansible.builtin.dnf:
    name: pinentry
  when: ansible_facts['os_family'] == 'RedHat'

- name: Ensure private directory on keys and secrets
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.gnupg/private-keys-v1.d"
    - "{{ ansible_user_dir }}/.keys"

- name: Install dev tools
  become: true
  ansible.builtin.dnf:
    name:
      - pipx
      - gcc
      - python3-pip
      - python3-devel

- name: Install python tools
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - black
    - pdm
    - pre-commit

- name: Skip loading bash settings if it is not interactive
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: BOF
    line: '[[ $- == *i* ]] || return  # return if it is not interactive'

- name: Setup TTY variable for gpg pinentry
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bash_profile"
    regexp: '^export GPG_TTY='
    line: 'export GPG_TTY=$(tty)  # Setup for pinentry'

- name: Enable ssh-agent on user login
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^eval \$?[`(]ssh-agent[`)]'
    line: 'eval `ssh-agent` > /dev/null  # Enable ssh-agent on startup'
