---
- name: Install collections and roles
  hosts: localhost
  connection: local
  tasks:
    - name: Install dependencies and collections
      community.general.ansible_galaxy_install:
        type: collection
        force: true  # force upgrade
        requirements_file: "{{ playbook_dir }}/../requirements.yml"

    - name: Install this collection
      vars:
        this_collection: git+https://github.com/ChunPanYung/ansi_colle-server.git
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ this_collection }},{{ git_branch | default('main') }}"
