---
- name: Test execution of role on localhost
  hosts: linux
  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"

  roles:
    - role: ansi_colle.server.kubernetes
      tags: kubernetes
