---
name: Validate Ansible Collection
'on':
  pull_request:
    branches:  # do not execute on master/main branch
      - master
      - main

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ansible.posix via Ansible Galaxy
        run: ansible-galaxy collection install ansible.posix
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
