---
name: Check git-cliff changelog Output
run-name: Check git-cliff output and save it to variable
'on': ['workflow_dispatch']
jobs:
  git-cliff-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
