---
- name: Retrieve information from github api
  ansible.builtin.uri:
    url: "{{ cloudflared_github_api }}"
    return_content: true
  register: cloudflared_api

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: cloudflared_tmpdir

- name: Download executables for linux x64 system
  ansible.builtin.get_url:
    url: "{{ cloudflared_api.json.assets[19].browser_download_url }}"
    dest: "{{ cloudflared_tmpdir.path }}/cloudflared.rpm"
    mode: '0644'

- name: Install cloudflared from rpm file
  become: true
  ansible.builtin.dnf:
    name: "{{ cloudflared_tmpdir.path }}/cloudflared.rpm"

- name: Create directory for cloudflared tunnel passphrase
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.cloudflared"
    state: directory
    mode: '0755'

- name: Create directory for cloudflared configuration
  become: true
  ansible.builtin.file:
    path: /etc/cloudflared/
    state: directory
    mode: '0755'

- name: Warning
  ansible.builtin.debug:
    msg: This role will only install cloudflared, it does not configure it.

- name: Remove temporary directory and its content
  ansible.builtin.file:
    path: "{{ cloudflared_tmpdir.path }}"
    state: absent
  when: cloudflared_tmpdir.path is defined
